# 集群更新存在一定风险，请谨慎操作

# 更新kubectl二进制
- hosts:
  - kube-master
  - kube-node
  - deploy
  - etcd
  - lb
  roles:
  - prepare
  tags: upgrade_k8s

# 更新etcd集群
- hosts: etcd
  roles:
  - etcd
  tags: upgrade_k8s

# docker更新，为保证不中断业务，不自动重启docker服务
- hosts:
  - kube-master
  - kube-node
  roles:
  - docker
  tags: upgrade_k8s

# 更新master节点
- hosts: kube-master
  roles:
  - kube-master
  - kube-node
  tags: upgrade_k8s

# 更新node节点
- hosts: kube-node
  roles:
  - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }
  tags: upgrade_k8s
