# 部分flannel配置，详见roles/flannel/templates/kube-flannel.yaml.j2

# 如果 node 节点有多块网卡，请设置 true
NODE_WITH_MULTIPLE_NETWORKS: "false"
 
# 设置flannel 后端
#FLANNEL_BACKEND: "host-gw"
FLANNEL_BACKEND: "vxlan"

#install_cni_image: "quay.io/coreos/flannel:v0.10.0-amd64"
install_cni_image: "jmgao1983/flannel:v0.10.0-amd64"

#flanneld_image: "quay.io/coreos/flannel:v0.10.0-amd64"
flanneld_image: "jmgao1983/flannel:v0.10.0-amd64"

# 离线镜像tar包
flannel_offline: "flannel_v0.10.0-amd64.tar"
